name: wasalni_app
description: "تطبيق Tariki للكابتن"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  google_maps_flutter: ^2.14.0
  geolocator: ^10.1.1
  image_picker: ^1.2.1
  provider: ^6.1.5+1
  intl: ^0.20.2
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpeg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpeg
