services:
  - type: web
    name: wasalni-backend
    runtime: docker
    plan: free
    region: frankfurt
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wasalni-db
          property: connectionString
      - key: PORT
        value: 80

databases:
  - name: wasalni-db
    plan: free
    databaseName: wasalni
    user: wasalni_user
