services:
  - type: web
    name: tariki-backend
    runtime: docker
    plan: free
    region: frankfurt
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tariki-db
          property: connectionString
      - key: PORT
        value: 80

databases:
  - name: tariki-db
    plan: free
    databaseName: tariki
    user: tariki_user
